Update cd2.yml

diff --git a/.github/workflows/cd2.yml b/.github/workflows/cd2.yml
--- a/.github/workflows/cd2.yml
+++ b/.github/workflows/cd2.yml
@@ -71,7 +71,7 @@ jobs:
             --output text)
       
           echo "Instance ID: $INSTANCE_ID"
-          sleep 5
+          sleep 10
       
           # Wait for the instance to be running
           aws ec2 wait instance-running --instance-ids $INSTANCE_ID
@@ -114,8 +114,13 @@ jobs:
           ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SSH_USER }}@${{ env.INSTANCE_PUBLIC_DNS }} << 'EOF'
   
           # Install Docker if not already installed
-          sudo yum install -y docker
-          sudo systemctl start docker
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing..."
+            sudo yum install -y docker
+            sudo systemctl start docker
+          else
+            echo "Docker is already installed."
+          fi
 
           # เพิ่มผู้ใช้ไปยังกลุ่ม docker
           sudo usermod -aG docker $USER
